"""The ocr_parser module organizes functions for parsing text generated by OCR conversion."""

def clean_substring(sub, string):
    """ clean_substring() removes internal spaces added by an OCR text conversion.

        For example, OCR libraries often place additional spaces around characters
        like '@' causing typical regular expressions for finding emails to fail.

        In cases where the substring is not in the string, the string is returned.

        Parameters
        ----------

        sub : str, required
            The substring we want to clean. '@' in the example.

        string: str, required
            The string containing the substring. A full email address for example.
    """
    idx = string.find(sub)
    beg = 0
    while idx != -1:        
        string = string[beg:idx].rstrip() + sub + string[idx+len(sub):len(string)].lstrip()
        beg = idx + len(sub)
        idx = string.find(sub,beg)
    return string
            

